### ISSUE TITLE
Backward compatibility broken in postTools

### ISSUE THREAD

**Issue by smattis** [UT-CHG/BET#151]
Be careful with old code using postTools. Recent additions by @lcgraham break backward compatibility. I didn't realize this when I merged it in because the tests were rewritten for the new syntax. I am going to make this more user friendly, but I guess I'll follow the new form.

**Comment by lcgraham** [comment]
I should have preserved backward compatibility. I'll try and take care of
this soon.

On Tue, Dec 1, 2015 at 4:57 PM Steven Mattis <notifications@github.com>
wrote:

> Be careful with old code using postTools. Recent additions by @lcgraham
> <https://github.com/lcgraham> break backward compatibility. I didn't
> realize this when I merged it in because the tests were rewritten for the
> new syntax. I am going to make this more user friendly, but I guess I'll
> follow the new form.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/UT-CHG/BET/issues/151>.
>
-- 

Lindley Graham, Ph.D. 2015

**Comment by smattis** [comment]
Actually, I'm already writing stuff assuming this version, so don't change it. This was meant to be kind of a warning if other people had issues. That's why I tagged as wontfix.

**Comment by lcgraham** [comment]
Ah I was just reading it in e-mail and didn't see the wontfix tag.
Technically we should increase the version number since backward
compatibility was broken, but that seems excessive for such a small change.

On Tue, Dec 1, 2015 at 6:18 PM Steven Mattis <notifications@github.com>
wrote:

> Actually, I'm already writing stuff assuming this version, so don't change
> it. This was meant to be kind of a warning if other people had issues.
> That's why I tagged as wontfix.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/UT-CHG/BET/issues/151#issuecomment-161128466>.
>
-- 

Lindley Graham, Ph.D. 2015

**Comment by lcgraham** [comment]
NON-BACKWARD COMPATIBLE CHANGES:
Comm.py -- method calls changed to match mpi4py updates
postTools.py -- sort_by_rho size of returned tuple increased by 1

CHANGES TO TESTS:
NEW -- test_indicatorFunctions.py
ADDED (2) -- test_plotDomains.py
MOD -- test_postTools.py (modified to match sort_by_rho return tuple)
ADDED (1) -- test_postTools.py, sample_prob, sample_lowest_prob

On Tue, Dec 1, 2015 at 6:20 PM lcgraham <lichgraham@gmail.com> wrote:

> Ah I was just reading it in e-mail and didn't see the wontfix tag.
> Technically we should increase the version number since backward
> compatibility was broken, but that seems excessive for such a small change.
>
> On Tue, Dec 1, 2015 at 6:18 PM Steven Mattis <notifications@github.com>
> wrote:
>
>> Actually, I'm already writing stuff assuming this version, so don't
>> change it. This was meant to be kind of a warning if other people had
>> issues. That's why I tagged as wontfix.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/UT-CHG/BET/issues/151#issuecomment-161128466>.
>>
> --
>
> Lindley Graham, Ph.D. 2015
>
-- 

Lindley Graham, Ph.D. 2015
