### ISSUE TITLE
Running tests in parallel for saving discretizations fails

### ISSUE THREAD

**Issue by smattis** [UT-CHG/BET#189]
Where it is freezing on the CI builds when running the tests in parallel also freezes up my machine.

**Comment by smattis** [comment]
@lcgraham A bunch of tests in `test_sample` and `test_basicSampling` and `test_adaptiveSampling` fail in parallel. In #190, I have commented out each of these tests and put a TODO for you. You should fix these, and after #190 is merged, you should do a pull request with tests that work. After #190 is merged, all tests in v2_master should be passing, and we should keep it that way for future pull requests.

**Comment by lcgraham** [comment]
Thank you I'll take care of them after #190 is merged. Sorry I didn't catch them earlier
