### ISSUE TITLE
general simpleFunP needed

### ISSUE THREAD

**Issue by eecsu** [UT-CHG/BET#196]
We should add a general simpleFunP such as

def user_discretization_user_distribution(data_set, output_probability_set, output_probability_emulated_sample_set)

Or something like the above. Basically this will handle all of the cases we currently do not have in the code. The user will generate an output_probability_set containing the sample_set (or discretization object) that discretizes the data space into Voronoi cells to be inverted. This may or may not contain probabilities. In the case where it does not, the user will also supply a sample_set (or discretization object) called output_probability_emulated_sample_set that contains samples of the data distribution to be binned in the Voronoi cells within the output_probability_set which then determine the probability values. This is essentially what I did in 

linearMap.py

in the validation example that is part of the recent pull request. It would be a pretty "simple" simpleFunP but offer a lot of flexibility for the types of distributions and discretizations we could use on the data space.

Thoughts?

**Comment by lcgraham** [comment]
I like this idea.

**Comment by lcgraham** [comment]
This will be marked as closed once #195 is merged.
