### ISSUE TITLE
v2 Beta Release

### ISSUE THREAD

**Issue by lcgraham** [UT-CHG/BET#202]
@eecsu thinks that we are ready for beta. Once Issues #200 are #199 resolved I think we are ready to merge this branch into master. We can then release it as v2.0.beta Then the remaining issues that are required for the Version 2.0 can be continuously integrated. Thoughts?

**Comment by eecsu** [comment]
@lcgraham I agree, and are you taking on these issues? I see you assigned #200 to yourself and it looks like the pull request fixes it. I have to go run an errand, can you take on #199 as part of the same pull request?.

**Comment by lcgraham** [comment]
I'll look into it.

On Wed, May 25, 2016 at 2:57 PM Troy Butler <notifications@github.com>
wrote:

> @lcgraham <https://github.com/lcgraham> I agree, and are you taking on
> these issues? I see you assigned #200
> <https://github.com/UT-CHG/BET/issues/200> to yourself and it looks like
> the pull request fixes it. I have to go run an errand, can you take on
> #199 <https://github.com/UT-CHG/BET/issues/199> as part of the same pull
> request?.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/UT-CHG/BET/issues/202#issuecomment-221672621>
>
-- 

Lindley Graham, Ph.D. 2015

**Comment by eecsu** [comment]
Do you want to do the honors of merging into master now and creating the v2.0.beta?

**Comment by smattis** [comment]
Hi. I agree that we are ready for v2 beta. I will review #203. Sorry I've been a little out of the conversation the last couple of days. As Lindley knows, I had to travel at the last minute for my grandfather's funeral.

**Comment by eecsu** [comment]
Hi Steve,

I am really sorry to hear that your grandfather passed away.

Sincerely,
Troy
