### ISSUE TITLE
Update plotDomains

### ISSUE THREAD

**Issue by eecsu** [UT-CHG/BET#206]
Should accept either discretization or sample_set objects and plots appropriate sample_set values based on name of plot function called if given a discretization object instead of a sample_set object.

Need to clean up the naming convention as well and optional keyword arguments to be consistent across all functions (some take img_folder but others do not). Some functions are named scatter2D* while others are scatter_2D*, etc. 

It is almost in the right format now, so just minor changes need to be made.

Base functions: scatter_2D, scatter_3D

All other functions call these (except for the triangulation of data domains if we still want to keep those). 

Perhaps rename the multi dimensional ones using "project_multi_dimensional" instead of just "multi" to make it more clear what is going on inside the functions that ultimately call scatter_2D or scatter_3D?

**Comment by lcgraham** [comment]
Modify plotDomain calls:
- `show_param(sample_disc, rho_D, p_ref, sample_nos, save, interactive, lnums, show dim)`
- `show_data(sample_obj, rho_D, Q_ref, sample_nos, save, interactive, Q_nums, show dim)`
        - combine show_param and show_data and add a flag for either input/output if given a discretization object
        - rename ``scatter_rhoD``
- `scatter_param_multi(sample_obj, img_folder, showdim, save, interactive)`
        - redundant remove
- `scatter2D_multi(sample_obj, color, p_ref, img_folder, filename, label_char, showdim)`
        - uses scatter_2D
        - rename scatter_2D_multi
        - change label_char to lambda_label

- add file extension to all calls in the module at the end of args
