### ISSUE TITLE
Updates to calculateP and logging

### ISSUE THREAD

**Issue by eecsu** [UT-CHG/BET#207]
Perhaps user should just call ``prob`` instead of ``prob_mc``. If the volumes are ``None``, then ``prob_mc`` is called and a warning is logged that a standard MC assumption on the volumes was used because no volume estimates were detected in the ``sample_set``. Less knowledge of the different functions is required by the user in this case. 

In the updated examples, I was explicit about the standard MC assumption being assumed true or false and setting the volumes accordingly to just use ``prob`` in either case.

**Comment by smattis** [comment]
Right now `prob` assumes volumes are already calculated and `prob_mc` uses volume emulation from a user-defined emulated sample set. I think we still want both of these options. Maybe for `prob`, if no volumes are defined we should use the mc assumption and give a warning. Should we rename `prob_mc` to `prob_emulate_volumes` or something?

**Comment by lcgraham** [comment]
I vote `prob`, `prob_with_emulated_volumes`, and `prob_on_emulated_samples`
