### ISSUE TITLE
update / add new .rst files for sensitivity

### ISSUE THREAD

**Issue by scottw13** [UT-CHG/BET#213]
update / add new .rst files for sensitivity

**Comment by lcgraham** [comment]
See #198

**Comment by lcgraham** [comment]
@scottw13, what's the status on this?

**Comment by scottw13** [comment]
Have not begun.  I haven't had a look at the updated examples that
Troy/Michael worked on yet.  I'll look at them on Monday and finish the
.rst files by then end of the week.

Scott
