### ISSUE TITLE
simpleFunP, vHist

### ISSUE THREAD

**Issue by mpilosov** [UT-CHG/BET#217]
the last few lines of ```voronoiHistogram``` ( in ```voronoiHistogram.simple_fun_uniform``` ) read as follows:
```
    s_set = samp.voronoi_sample_set(dim=points.shape[1])
    s_set.set_values(points)
    s_set.set_probabilities(rho_D_M)
    return s_set
```

Then simpleFunP.regular_partition_uniform_distribution_rectangle_size ends with (line 361-3):
```
    if isinstance(data_set, samp.discretization):
        data_set.set_output_probability_set(s_set)
    return s_set
```
but the method ```set_output_probability_set()``` in the ```discretization``` object wants a ```sample_set_base``` type input argument, not a ```voronoi_sample_set``` type. 

This of course leaves ```mydiscretization._output_probability_set``` empty and so ```mydiscretization``` cannot be passed into ```calculateP.prob()```

I thought to comment out the lines and just return the s_set object from my call:
```
s_set = simpleFunP.regular_partition_uniform_distribution_rectangle_scaled(
    data_set=my_discretization, Q_ref=Q_ref, rect_scale=bin_ratio, 
    center_pts_per_edge = 1)
```
but investigating in ipython, oddly enough I found the ```s_set``` object to be a ```KDTree``` which is the return of the ```query``` method in the ```voronoi_sample_set```class definition. This is so weird. I've had no trouble with returning and then using ```sample_set``` objects, which all appear to be ```voronoi_sample_set``` objects anyway, so why is my returned s_set a KDTree instead of a sample object?

**Comment by mpilosov** [comment]
Okay so the culprit ended up being these compilation issues I've been running into wherein the built version doesn't really work unless I maybe go into a file, add in a whitespace somewhere in a function that caused an error message, save the file, and run setup.py install again. 
I've run into this a lot, and it caused the issue above. As if it were looking at an older version of the modules instead of the ones the last setup should have directed it to use. 
For example, once I added a white space and re-setup BET, I ran into an error in my script for sample_highest_prob(), which again I found, added a whitespace, and rebuilt BET and then my script worked.

Should I not be running python setup.py install every time I make a change to some module? Is there something like an update? Why is this happening?

**Comment by mpilosov** [comment]
PS line 103 in calculateP seems unnecessary.

**Comment by smattis** [comment]
`voronoi_sample_set` is a set of type `sample_set_base` so that is not a problem. 

Do you have the environment variable `PYTHONPATH` set somewhere in some older version of BET? Are you sure you are using the same python to build and run the code? 

Whitespace in the docstring like that within line 103 in calculateP is not really an issue.

**Comment by mpilosov** [comment]
sorry was looking at an older version. few lines down. discretization.check_nums() is what I was referring to. line 75 is the one I meant in the latest master. the whitespace wasn't in docstrings. I would add a space after a comma or something in a function definition and then save and recompile to make things work.

python is the same throughout. 

it also appears all the work I've done today getting the sensitivity examples to work was uneccesary, as Lindley fixed those all last week. I really need to get the upstream updates much more often...

**Comment by lcgraham** [comment]
@mpilosov, both linear_skewness_binratio.py and linear_measure_binratio.py run for me. When you fetched from upstream did you also [merge](https://help.github.com/articles/syncing-a-fork/) before re-installing?

**Comment by smattis** [comment]
discretization.check_nums() is actually very important. It runs a check to make sure all dimensions are correct and raises an exception if they are not.

I can run the `linear_skewness_binratio.py` perfectly fine with the current version of master. Are you running on your fork?

**Comment by lcgraham** [comment]
Yes, making sure to keep informed of changes to the code is important when you're planning on tackling an issue or adding new functionality especially during a large refactoring like now. Most of the discussion regarding issues/updates to the code happens in the [issues](https://github.com/UT-CHG/BET/issues) section, but a good quick visual check of the various [forks](https://github.com/UT-CHG/BET/network) can quickly show the status of the main repo AND other contributor's forks. Also the [homepage](https://github.com/UT-CHG/BET) of the repo always lists and highlights the latest commit to the master branch. If you're going to tackle an [issue](https://guides.github.com/features/issues/) or want to double check that someone isn't already working on an issue you can check to see who's [assigned to an issue](https://help.github.com/articles/assigning-issues-and-pull-requests-to-other-github-users/) or assign yourself.

**Comment by mpilosov** [comment]
steve - thanks, I see that now. I was only looking at the output of check_nums()
I did merge before reinstalling, yes. 
I just re-performed 
```
git fetch upstream
git merge upstream/master
```
and received "Already up-to-date' as a response.
Then I ran 
```python setup.py install``` and saw "Finished processing dependencies for bet==2.0.0-beta" as a response.
```nosetests``` ran smoothly.
```python examples/sensitivity/linear/linear_skewness_binratio.py``` still returns the item assignment error message. =(
I am running all of this from my own fork, but from the master branch. Is that a problem if it appears to be up to date?

I really appreciate the (extremely expedient) feedback, guys. Hopefully once I get myself up and running, I can actually start making meaningful contributions.

**Comment by mpilosov** [comment]
I mean, should I just delete what I have (saving my contributions elsewhere, most of them are deprecated now anyway) and re-fork... try this again from scratch?

**Comment by lcgraham** [comment]
You can use git diff to compare branches/files/etc. What I think is happening is that you've made some changes in this branch which do not conflict with the changes on the master. However, these changes cause your local branch (and the branch on your fork) to differ from the master branch of the upstream repo. If you want to keep the changes you've made and work on this same branch you should probably be able to figure out what's going on using [git diff](https://git-scm.com/docs/git-diff) and [pdb](https://docs.python.org/2/library/pdb.html).

No need to refork! In fact, if you want to start from a clean slate, the best thing to do in terms of learning would be to simply create a new [branch](https://git-scm.com/book/en/v2/Git-Branching-Remote-Branches) on your fork and start from there. This way you don't loose a record of what you've done, especially if you want to keep/reuse whatever work you've currently done. 

1. Find a "clear" the commit you'd like to start from. This is probably before you started making changes.
2. Check out that commit.
3. Create a new branch from that commit.
4. Merge upstream/master into this commit.
5. Push this branch to your fork and set up this branch to track from your fork.
6. Start making changes and commits.

**Comment by lcgraham** [comment]
@mpilosov is this resolved? If so please close the issue. Thanks.

**Comment by mpilosov** [comment]
Yes. Thanks so much for your help!
