### ISSUE TITLE
Update inheritance

### ISSUE THREAD

**Issue by lcgraham** [UT-CHG/BET#228]
Make sure that child classes are using the proper super methods, especially for initialization. The way things are currently written works, but we should be using `super(my_class_name, self).__init__(*args)` or ``super(my_class_name, self).method_name(*args)`.

**Comment by smattis** [comment]
It's a difference of "new-style" python and "old-style." I actually prefer old-style because I think it looks cleaner and requires less code, but we should be consistent.
