### ISSUE TITLE
Parallelization in simpleFunP inconsistent

### ISSUE THREAD

**Issue by lcgraham** [UT-CHG/BET#230]
I think the parallelization in `bet.calculateP.simpleFunP` is inconsistent with the way things are parallelized in `calculateP` and `sample.py`. The current implementation gives correct answers, thus it passes the tests, but I think the implementation should more closely match that of `calculateP` and `sample.py`. Notably, `num_d_emulate` is interpreted as the number of emulated samples per processor NOT the global number of emulated samples. Also there is no use of `_values_local` or `global_to_local`.

**Comment by smattis** [comment]
I agree that it should be cleaned up a bit; however, I wouldn't not call this a bug.

**Comment by eecsu** [comment]
Are you sure ``num_d_emulate`` is interpreted as the number of emulated samples per processor? In all functions where it is an actual input, I eventually can find an instance of ``num_d_emulate = int(num_d_emulate / comm.size) + 1`` which would mean that the input is actually the global number of emulated points, which is then distributed into smaller chunks among the the processors via the ``d_distr_emulate`` which uses this now modified value of ``num_d_emulate``. Am I missing something?

**Comment by lcgraham** [comment]
@eecsu You're right. It is actually the global number of emulated points. It would be good to update it though so that ``num_d_emulate`` is not rounded to the nearest whole number multiple of the number of processors.

**Comment by eecsu** [comment]
@lcgraham You want to use modulo arithmetic? We could do that. 

The other part you suggested involving using ``_values_local`` and ``global_to_local`` are less clear to me. We need each processor to have a fully copy of the partitioning points in the data space, but each only needs a portion of the emulated points to bin into the implicit cells defined by the partitioning points. I guess what happens now is that each processor then ends up with a full copy of the simple function approximation, but isn't this necessary for the ``calculateP`` part to work? I worked myself into a bit of a circle looking at it earlier. What do you think? I would like @smattis to chime in when he gets a chance. Everything is working now, so no hurry.

**Comment by lcgraham** [comment]
Yes, I'd like to use modulo arithmetic.

You can ignore the part about `_values_local` and `global_to_local` since the main goal is conformity. I was thinking there was a way to increase the parallelism, but it doesn't make sense.

**Comment by smattis** [comment]
I agree that it should be done in the same way that we handle integration for volume emulation. I'll assign myself since I worked on simpleFunP.
