### ISSUE TITLE
Scatter plots of QoI and parameter samples

### ISSUE THREAD

**Issue by eecsu** [UT-CHG/BET#232]
Using scatter_2D and scatter_3D as the base, we should just have functions

scatter_2D_parameters
scatter_2D_data
scatter_3D_parameters
scatter_3D_data

that simply call the base functions. They should all read in either sample_obj or sample_discretization and if the sample_discretization is called, then the correct sample_obj is extracted from the discretization object and sent to the correct scatter function. Make sense?

**Comment by lcgraham** [comment]
I think these methods should be renamed input/output instead of parameters/data. Also I think they only make sense for discretization objects. Does scatter_rhoD not provide the functionality you're looking for?

**Comment by eecsu** [comment]
The eps also didn't work for the rhoD but mainly just looking for simple
functionality. I like your naming suggestions.

**Comment by lcgraham** [comment]
Oops, I'll fix it and add a note to the documentation that you can specify the file extension in either the file name or the by using the file extension but not do both.

**Comment by lcgraham** [comment]
Right now the default file extension is png in plotDomains and eps in plotP. I need to update it so that it's a blank string and specify that you need to put ".extension_abreviation" to specify or add one to the file name, but not both.

**Comment by lcgraham** [comment]
By the way, difference in the calls would be 'scatter_2D(stuff, my_disc.get_input_sample_set(), more_stuff)' vs. 'scatter_2D_input(stuff, my_disc, more_stuff)'. Plus if you wanted to plot any of the emulated samples you'd need to do the first call anyways.
