### ISSUE TITLE
Create a type of sample histogramming and computeProbSet in postTools

### ISSUE THREAD

**Issue by eecsu** [UT-CHG/BET#241]
We should create a tool for defining histograms based on a set of samples defining the bins. It would look kind of like the ``user_partition_user_distribution`` in ``simpleFunP``. We should not limit ourselves to just computing marginals and/or defining histograms on regular grids. This can be a way to post-process the probability measure to determine the probabilities on some non-structured partitioning of the space, and also allows us to define either marginals and/or histograms more easily in higher dimensions. 

This moves us towards the functionality of a ``computeProbSet`` type function. The idea is that the user defines an event of interest in terms of some union of truncated Voronoi cells specified by a set of of samples + distances (with a metric) defining the truncated Voronoi cells in the domain for which the probability is desired. This would have very similar functionality to the sample histogramming except that an entire partitioning of the space would not be required.

**Comment by lcgraham** [comment]
Once #250 is merged then this should be named ``prob_regions`` and ``prob_regions_with_emulated_samples``

**Comment by lcgraham** [comment]
This is resolved by #250
