### ISSUE TITLE
cartesian_sample_set documentation

### ISSUE THREAD

**Issue by mpilosov** [UT-CHG/BET#253]
The description seems to me to be really unclear, and it took me an embarrassingly long time to deduce what the inputs should look like. 

I found that `xi = [ x-coordinates, y-coordinates, z-coordinates, etc]` was correct, which doesn't seem to be what the documentation states (" array_like `x1, x2, ... xn` "). 

which I think more readily suggests `x1 = [x_1, y_1], x2 = [x_2, y_2]`, etc.

I think it would be helpful to change the documentation to reflect (what I believe to be) the intended usage of 
`xi = [meshgrid(range, parts), meshgrid(range, parts), etc.] `

**Comment by smattis** [comment]
That documentation is lifted from meshgrid (http://docs.scipy.org/doc/numpy/reference/generated/numpy.meshgrid.html) which is a really common numpy function (also very similar to the Matlab function) and this is modeled after that. It is a little confusing, but is a really common, concise way to define cartesian grids. We could add a link to the meshgrid documentation.

**Comment by mpilosov** [comment]
Ahhhhh. That makes a lot more sense. I frequently use meshgrid (albeit with one argument), and having a link to that documentation might indeed have made the connection click a lot sooner.

Thanks for the quick reply Steve. Sorry, I wasn't sure it was a real issue worth posting here, but I was just trying to consider what an end user might experience when looking at it and I do think a little more documentation can go a long way.

Not sent from my computer.

On Jul 20, 2016, at 20:33, Steven Mattis <notifications@github.com<mailto:notifications@github.com>> wrote:


That documentation is lifted from meshgrid (http://docs.scipy.org/doc/numpy/reference/generated/numpy.meshgrid.html) which is a really common numpy function (also very similar to the Matlab function) and this is modeled after that. It is a little confusing, but is a really common, concise way to define cartesian grids. We could add a link to the meshgrid documentation.

-

**Comment by lcgraham** [comment]
I think adding a link as a seealso would be a good idea.
