### ISSUE TITLE
save_discretization does not overwrite files

### ISSUE THREAD

**Issue by smattis** [UT-CHG/BET#259]
`bet.sample.save_discretization` is not overwriting .mat files if they already exist. Look at the code:

```
import numpy as np
import numpy.random as rand
import bet.sample as samp


iss = samp.sample_set(3)
iss.set_values(rand.random((100,3)))
oss = samp.sample_set(2)
oss.set_values(rand.random((100,2)))
disc = samp.discretization(input_sample_set=iss,
                    output_sample_set=oss)

samp.save_discretization(disc, "test")

iss = samp.sample_set(3)
iss.set_values(rand.random((200,3)))
oss = samp.sample_set(2)
oss.set_values(rand.random((200,2)))
disc = samp.discretization(input_sample_set=iss,
                    output_sample_set=oss)

samp.save_discretization(disc, "test")

disc_new = samp.load_discretization("test")
print disc_new._input_sample_set._values.shape
```

It outputs (100,3 ) and the values are the same as the first discretization.

**Comment by smattis** [comment]
The culprit is here https://github.com/UT-CHG/BET/blob/master/bet/sample.py#L85 
The dictionary update will revert any key/value pairs back to the old saved dictionary if it existed before.

**Comment by lcgraham** [comment]
Solution:

```
            mdat = sio.loadmat(local_file_name)
            mdat.update(new_mdat)
            sio.savemat(local_file_name, mdat)
```

**Comment by lcgraham** [comment]
This should be applied in both save_sample_set and save_discretization. Good catch!

**Comment by smattis** [comment]
I think that `save_discretization` should save the given discretization as it is to the filename given, overwriting anything that already has that name. Loading the file with the filename if it exists and updating it seems dangerous.  Say I have a saved discretization with only input and output sample sets that have values and error estimates. Now, if I try to save another discretization with input and output sample sets that only have values, it will save them with the values error estimates from the previous discretization. Even if we prevented it from copying the values, it would copy the error estimates. Does this make sense?

**Comment by lcgraham** [comment]
Yes, this makes sense I will submit a proposed fix shortly.

**Comment by smattis** [comment]
Cool. Should be pretty simple. Mostly deletion.
