### ISSUE TITLE
new issue

### ISSUE THREAD

**Issue by lcgraham** [UT-CHG/BET#265]
@eecsu Can you add that issue that we spoke about yesterday?

**Comment by eecsu** [comment]
There was the contaminant transport rst files (just raised an issue for that and I know Steve was working on those Wednesday). 

The sensitivity examples need to be updated with documentation as well and I will get on that soon (issue already exists).

The other was the center_pts_per_edge for the rectangle sample set used in the discretization of a uniform distribution on a rectangle. Will submit that issue right now.
