### ISSUE TITLE
top_percentile=1.0 returns all samples, postTools.sample_highest_prob

### ISSUE THREAD

**Issue by scottw13** [UT-CHG/BET#29]
In postTools.sample_highest_prob, if you set top_percentile=1.0, it returns the correct volume of the region in Lambda, but it return num_samples= all samples.  It looks like this is because in line 63 postTools

num_samples = np.sum(P_sum <= top_percentile)

So Psum is always <= 1.0, and it returns all samples.  Maybe <= top_percentile - epsilon, or an

if top_percentile==1.0
    num_samples = numbers of nonzeros in P_samples

**Comment by lcgraham** [comment]
Sounds good to me. I've fixed it and a few other things in a commit. I'll put in a pull request in a bit.

**Comment by smattis** [comment]
This is fixed in the pull request that I just submitted.

**Comment by scottw13** [comment]
Great.  Thanks Lindley.

Scott

**Comment by lcgraham** [comment]
Don�t thank me. Steve fixed it.

Lindley Graham
lichgraham@gmail.com
