### ISSUE TITLE
v2.1.0/1 tag?

### ISSUE THREAD

**Issue by mathematicalmichael** [UT-CHG/BET#304]
How do tags work on here? I incremented versions in the `setup.py` file but the "tags" dropdown menu in github doesn't show anything.

**Comment by smattis** [comment]
We agreed that we were going to stop doing tags and releases on github starting with v2.0.0. As long as we keep backward compatibility and keep doing good CI practices, it isn't really necessary. Also, new releases create new DOIs which in theory is nice, but we want people to keep citing the current v2.0.0 DOI for now.

**Comment by mathematicalmichael** [comment]
Thanks for the clarification. Troy asked me about it a while ago and I forgot to look into it. Much appreciated.
