### ISSUE TITLE
FEniCS examples fail

### ISSUE THREAD

**Issue by mathematicalmichael** [UT-CHG/BET#323]
inconsistent use of tabs/spaces. Seems like my auto-linting did not actually go deep enough in its recursion of folders. Completely missed these files. I believe that a pass through autopep should be able to fix this.

Minimal steps to reproduce issue (fresh env):
```
git clone https://github.com/UT-CHG/BET.git
cd BET/
python setup.py install
python examples/FEniCS/projectKL.py
```

Came across it by accident as I was getting bored of running the same examples and realized I had never played around with this folder at all. @eecsu 

I'll go ahead and submit a PR just for this folder.

**Comment by mathematicalmichael** [comment]
confirmed: linting did address this bug.

However, still unable to run `BET_script.py`

here's a quick debugging tip: open the binder, open the python files, right click "create console for editor" , select all code in the python file, hit ctrl+enter. The console is dedicated to this file alone.

**Comment by mathematicalmichael** [comment]
furthermore, and this may be related to the error in `BET_script.py`: when trying to run `myModel_serial.py`, I get `FileNotFound` for the `KL_expansion.mat` file. I assume that's because there was an error in it's creation in the aforementioned script file.

**Comment by eecsu** [comment]
https://github.com/UT-CHG/BET/pull/324 addresses this
