### ISSUE TITLE
segmention of examples

### ISSUE THREAD

**Issue by mathematicalmichael** [UT-CHG/BET#332]
https://github.com/UT-CHG/BET/blob/master/examples/plotting/Plotting_Examples.ipynb previews like this are nice, but it clutters up this repository with the large commits. 

I suggest we remove notebook examples and move them to a separate repo. We can decide if it is worth keeping any python script examples here or if we should move those too. The thinking is that someone can clone or explore the examples repo and run everything after calling `pip install bet` (amazingly... this name IS available). 

Small changes to make examples nicer requires a different travis file that attempts to install bet with pip and run all of them would make the CI more robust. Perhaps a shell script that handles the logic of running them all can be the thing Travis attempts to execute, and function as a test. Or is it possible to write unit tests that just check if python files run without errors?

the fenics example really just deserves to have its own repository entirely, since it effectively builds out a module that is just without unit tests. @eecsu and I briefly discussed moving it into a separate project and adding appropriate usage documentation.

**Comment by eecsu** [comment]
I agree with this idea. I think the fenics example ought to have a separate repo as well since it has fenics as a dependency, which can cause all sorts of issues for people. I would have the python scripts and notebooks together in a separate repo just to make sure they stay in sync.

**Comment by mathematicalmichael** [comment]
Yeah, we can set up a dockerfile so binder can build fenics and let people try it out. Summer?

MP

**Comment by mathematicalmichael** [comment]
examples have been removed in `master` through #382
