### ISSUE TITLE
failing build due to #329

### ISSUE THREAD

**Issue by mathematicalmichael** [UT-CHG/BET#335]
@smattis I looked at the logs and can't really understand what happened to make the tests fail in parallel for Python 3. 

Could we discuss how to go about fixing this? I really want to understand this stuff. It was passing before/after merge... Then suddenly... nope.

**Comment by mathematicalmichael** [comment]
more from the trace:
```
root: INFO: COLD START
root: INFO: Current chain length: 5/10
root: INFO: Current chain length: 10/10
root: INFO: No sample_set named default_emulated_input_sample_set with _dim in file
root: INFO: No sample_set named default_emulated_output_sample_set with _dim in file
root: INFO: No sample_set named default_output_probability_set with _dim in file
root: INFO: COLD START
root: INFO: Current chain length: 5/5
root: INFO: HOT START from partial run
root: INFO: HOT START using parallel files (diff nproc)
--------------------- >> end captured logging << ---------------------
```
was a file removed somehow? I can't make sense of these errors. Maybe mpi was updated?

**Comment by mathematicalmichael** [comment]
parallel tests are passing in my environment. This is confusing. 
`mpirun -n 2 nosetests -v test/test_sampling/test_adaptiveSampling.py`

Packages:
`pyDOE` is up to date.
`numpy` 1.15.4 => 1.16.3
`scipy` 1.2.1 => 1.3.0

once updated, tests fail. now seeing the same message as Travis

oddly... when i downgrade back, tests still fail. that is very weird. VERY weird. something clearly happened between successive runs of tests (save/load?) that caused a problem. 

going to clone fresh and try again.

**Comment by mathematicalmichael** [comment]
the errors are different between versions of numpy/scipy though.

with downgraded versions:
```
AssertionError:
Arrays are not equal

(shapes (100, 1), (50, 1) mismatch)
 x: array([[0.763331],
       [0.902814],
       [0.851083],...
 y: array([[0.138951],
       [0.94485 ],
       [0.617164],...
-------------------- >> begin captured stdout << ---------------------
dim (1, 2)
COLD 0
```

```
root: INFO: COLD START
root: INFO: Current chain length: 5/10
root: INFO: Current chain length: 10/10
root: INFO: No sample_set named default_emulated_input_sample_set with _dim in file
root: INFO: No sample_set named default_emulated_output_sample_set with _dim in file
root: INFO: No sample_set named default_output_probability_set with _dim in file
root: INFO: COLD START
root: INFO: Current chain length: 5/5
root: INFO: HOT START from partial run
root: INFO: HOT START using parallel files (same nproc)
```

with upgrade:
```
bet.sample.length_not_matching: length of _right inconsistent with _values
-------------------- >> begin captured stdout << ---------------------
COLD 1
COLD then 1
1

--------------------- >> end captured stdout << ----------------------
-------------------- >> begin captured logging << --------------------
root: INFO: COLD START
root: INFO: No sample_set named default_emulated_input_sample_set with _dim in file
root: INFO: No sample_set named default_emulated_output_sample_set with _dim in file
root: INFO: No sample_set named default_output_probability_set with _dim in file
root: INFO: COLD START
root: INFO: HOT START using parallel files (same nproc)
--------------------- >> end captured logging << ---------------------
```

**Comment by mathematicalmichael** [comment]
unfortunately I do not understand exactly what the HOT/COLD outputs mean. Any ideas of what might be happening?? @smattis @eecsu 

hard for me to test any new code since the old tests somehow started failing =/

**Comment by mathematicalmichael** [comment]
reverting to earlier commits DOES NOT fix the problem. The builds were passing for the past three weeks. This is almost certainly due to an upgrade somewhere... I tried five different earlier commits. all same errors.

**Comment by mathematicalmichael** [comment]
okay here's how I got them to pass on the latest commit:
- fresh clone = > fail.
- upgrade numpy/scipy
- DELETE any files generated by tests. find them ALL and remove them.
- re-run. Now pass.

this passes. so my hypothesis is that some files being generated are sticking around inappropriately between tests in parallel. watching the directory tree during parallel tests, I notice a bunch being generated and removed. maybe some just not quite in time? 

Okay, well... now that this is passing and packages are upgraded... how can I reproduce the errors occurring in Travis? Well... Travis runs serial tests first, then parallel. Let's try that? I see that serial tests also fail after the parallel so I suspect this is all related. incomplete files are loaded and that is what presents the "not found" error messages.

ran serial (pass.. do not see extra files other than images*), 

then parallel to match Travis... 
well, they also pass. darn. i don't understand. I didn't change a single file! 
okay... let's try this again. numpy/scipy are already upgraded. let's clone fresh again and re-run tests in serial then parallel. If that passes then I'm at a total loss... 



*Also PS two png files stick around in the root directory that probably do not belong. need to remove them during teardown of tests.

**Comment by mathematicalmichael** [comment]
**ONLY NEED TO READ THIS**

fresh clone. with downgraded numpy/scipy, serial and then parallel...

serial pass.
parallel pass.

upgrade scipy.
parallel FAIL

DELETE FILES left over.
downgrade scipy. 
parallel PASS.

_I think we've honed in on it... scipy upgrade is the problem? Let's make sure._

upgrade numpy.
parallel PASS.

OKAY. SO.... IT IS SCIPY, @smattis. something here... https://docs.scipy.org/doc/scipy/reference/release.1.3.0.html is causing failures.

let us attempt to get more specific...
upgrade `scipy==1.3.0rc1` (first past `1.2.0`) => FAIL.

okay. So, I'm going to version-lock scipy for the time being until we can track this down to the specific method causing problems.

**Comment by eecsu** [comment]
Scipy 1.2.1 was already pretty recent. Right now, I think we only need scipy 1.2.1 for GKDE when we incorporate the density-based sample algorithms (assuming we want weighted GKDE as an option, which I do). So, if we lock it for now at 1.2.1 this should be sufficient moving forward in the foreseeable future.

**Comment by mathematicalmichael** [comment]
`grep -rni “scipy” bet/`
we use it in a number of places. `scipy.spatial` is used for nearest-neighbor. `scipy.fftpack` is used in plotting, etc. 
best course of action is to track down the problem and keep following their upgrades. The version-lock is only a band-aid.

**Comment by mathematicalmichael** [comment]
better search:
using `ripgrep` from `BET`, already acts recursively, prints line numbers, and is technically faster

```sh
rg "scipy"
```
