### ISSUE TITLE
How we do installs

### ISSUE THREAD

**Issue by mathematicalmichael** [UT-CHG/BET#356]
Currently we are doing `python setup.py install` as per our README.

I propose we change this to `pip install .` since this will ACTUALLY downgrade packages that we version-lock. This explains a number of things, namely the issues involved in trying to debug any of #335 #355 #333, which were all in some way heavily dependent on `scipy==1.2.1.` version lock introduced in #337, and is related to the proposal to change travis in #322 

By using `pip install .`, you can validate version-downgrades with ipython immediately using `import` and `.__version` as such:
```python
import scipy
print(scipy.__version__)
```

**Comment by mathematicalmichael** [comment]
a PR to address this would include changes to 
- `README.md`
- `.travis.yml`

**Comment by smattis** [comment]
Yes, we should do this. Also, we should looking into adding to the Python Package Index and conda forge for version 3.

**Comment by mathematicalmichael** [comment]
I have been practicing packaging new projects and CI pipelines. I'll be ready with templates very soon.

**Comment by mathematicalmichael** [comment]
testing requirements will be stripped out and only installed for travis. running `pip install .` should not carry with it `pytest`
