### ISSUE TITLE
Deprecate adaptive sampling?

### ISSUE THREAD

**Issue by smattis** [UT-CHG/BET#366]
We discussed deprecating adaptive sampling because it is causing big issues with tests passing and isn't playing well with new versions of `scipy`.  In the least, the hot starting capabilities could be deprecated because most of the i/o related to that is causing the problems. Also, it has not been actively used in a long time.

**Comment by mathematicalmichael** [comment]
I dug into these issues a lot (threw observations into comments). 
I think I figured out the source but don't know that I can fix it. 

However, #360 may resolve it. if we move away from `mat` files, all the hotstart issues may be resolved from that.

**Comment by mathematicalmichael** [comment]
officially will be deprecated in v3.

**Comment by smattis** [comment]
Can you not close these issues please. They will be closed automatically
when the big PR is merged!
