### ISSUE TITLE
Parallel Tests

### ISSUE THREAD

**Issue by mathematicalmichael** [UT-CHG/BET#396]
@smattis from what I see in the travis file, `mpirun -n 2 pytest` is how we're doing parallel tests. 
However, I don't think Travis actually has real multicore. I'm not getting the tests to pass in parallel on my machine for n>2, is it working for you? Is it not supposed to?

**Comment by smattis** [comment]
@mathematicalmichael They all just passed with n=4 on my laptop.

**Comment by mathematicalmichael** [comment]
hmmm. thank you, that helps. 
what's your base OS?

I'm running ubuntu focal and doing my testing in docker built on the same (meaning, my `apt/sources/lists.d` all point to the newest versions of `mpich` published in the PPAs.

**Comment by smattis** [comment]
macOS Catalina with somewhat older mpich libraries. It worked with Xenial (with Travis) and Bionic (with Github Actions) during the CI testing. 

From my experience, if the test pass in "parallel" on one core using multiple threads, which is what mpirun does if you give an n greater than the number of cores available, then they will pass on a multicore system.

What do the errors look like?

**Comment by mathematicalmichael** [comment]
https://github.com/mathematicalmichael/BET/runs/861340623?check_suite_focus=true

my machine doesn't have multi-threading. straight up 8 cores.

**Comment by mathematicalmichael** [comment]
relevant sections

```
test/test_sampling/test_useLUQ.py:56: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
bet/sampling/useLUQ.py:141: in learn_qois_and_transform
    self.learn.learn_qois_and_transform(**kwargs)
/usr/local/lib/python3.8/dist-packages/luq/luq.py:714: in learn_qois_and_transform
    self.learn_qoi(
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <luq.luq.LUQ object at 0x7f536c031d30>, variance_rate = None
proposals = ({'kernel': 'linear'}, {'kernel': 'rbf'}, {'kernel': 'sigmoid'}, {'kernel': 'poly'}, {'kernel': 'cosine'})
num_qoi = 2
```

```
>               self.kpcas.append(kpcas_local[ind_best])
E               TypeError: list indices must be integers or slices, not NoneType

/usr/local/lib/python3.8/dist-packages/luq/luq.py:632: TypeError
```


and this, I don't think is actually failing, maybe capturing the F from the wrong stdout? I can't tell, but it looked "fail-like" as it was running (towards the top), before all the LUQ-related printouts.

```
test/test_sensitivity/test_chooseQoIs.py ..F
```

**Comment by smattis** [comment]
Ok. I see what is happening with a lot of this. Most of this is easy to fix. The testing of `useLUQ` can have a decorator added to only run in serial. It does not have parallel support.

**Comment by mathematicalmichael** [comment]
ahhh.

**Comment by smattis** [comment]
What you said is basically correct. It was running the exact same thing on each processor and the stdout got jumbled somehow. But really, no reason to run this in parallel.

**Comment by mathematicalmichael** [comment]
(sorry I keep linking you to GH actions instead of Travis, but I'm finding it easier to trigger jobs with it on my fork than Travis is, though I think I've finally figured out why just from practicing with another tool). 

also, I went wild with Travis once so I could figure out cross-platform testing: https://github.com/mathematicalmichael/spellfix/blob/master/.travis.yml let me know if you have any interest in adding OSX or Windows testing (I know it's a preference thing, just thought I'd offer).

**Comment by mathematicalmichael** [comment]
is it possible to add a decorator to LUQ to also prevent all the printout/logging (maybe log to file instead) during testing? makes the stacktrace really painful to parse

**Comment by smattis** [comment]
#397 should handle the useLUQ tests

**Comment by smattis** [comment]
Already have an issue opened in LUQ regarding this https://github.com/CU-Denver-UQ/LUQ/issues/6. Will try to get to it soon.

**Comment by smattis** [comment]
@mathematicalmichael Update and try with n=4 again.

**Comment by mathematicalmichael** [comment]
- [ ] `n=2`

- [ ] `n=3`

- [ ] `n=4`

- [ ] `n=5`

- [ ] `n=6`

- [ ] `n=7`

- [ ] `n=8`

**Comment by mathematicalmichael** [comment]
`n=8` failed, rest were good.

```
test/test_calculateP/test_calculateP.py:71: AssertionError
=========================== short test summary info ============================
FAILED test/test_calculateP/test_calculateP.py::Test_prob_10to4::test_prob_sum_to_1
FAILED test/test_calculateP/test_calculateP.py::Test_prob_on_emulated_samples_10to4::test_P_sum_to_1
FAILED test/test_calculateP/test_calculateP.py::Test_prob_with_emulated_volumes_10to4::test_P_sum_to_1
================== 3 failed, 379 passed, 18 skipped in 41.30s ==================
...........                                          [100%]

=================================== FAILURES ===================================
______________________ Test_prob_10to4.test_prob_sum_to_1 ______________________

self = <test.test_calculateP.test_calculateP.Test_prob_10to4 testMethod=test_prob_sum_to_1>

    def test_prob_sum_to_1(self):
        """
        Test to see if the prob. sums to 1.
        """
>       nptest.assert_almost_equal(np.sum(self.inputs._probabilities), 1.0)
E       AssertionError: 
E       Arrays are not almost equal to 7 decimals
E        ACTUAL: 0.0
E        DESIRED: 1.0

test/test_calculateP/test_calculateP.py:31: AssertionError
_____________ Test_prob_on_emulated_samples_10to4.test_P_sum_to_1 ______________

self = <test.test_calculateP.test_calculateP.Test_prob_on_emulated_samples_10to4 testMethod=test_P_sum_to_1>

    def test_P_sum_to_1(self):
        """
        Test that prob. sums to 1.
        """
        self.inputs_emulated.local_to_global()
>       nptest.assert_almost_equal(
            np.sum(self.inputs_emulated._probabilities), 1.0)
E       AssertionError: 
E       Arrays are not almost equal to 7 decimals
E        ACTUAL: 0.0
E        DESIRED: 1.0

test/test_calculateP/test_calculateP.py:53: AssertionError
____________ Test_prob_with_emulated_volumes_10to4.test_P_sum_to_1 _____________

self = <test.test_calculateP.test_calculateP.Test_prob_with_emulated_volumes_10to4 testMethod=test_P_sum_to_1>

    def test_P_sum_to_1(self):
        """
        Test that probs sum to 1.
        """
>       nptest.assert_almost_equal(np.sum(self.inputs._probabilities), 1.0)
E       AssertionError: 
E       Arrays are not almost equal to 7 decimals
E        ACTUAL: 0.0
E        DESIRED: 1.0

test/test_calculateP/test_calculateP.py:71: AssertionError
=========================== short test summary info ============================
FAILED test/test_calculateP/test_calculateP.py::Test_prob_10to4::test_prob_sum_to_1
FAILED test/test_calculateP/test_calculateP.py::Test_prob_on_emulated_samples_10to4::test_P_sum_to_1
FAILED test/test_calculateP/test_calculateP.py::Test_prob_with_emulated_volumes_10to4::test_P_sum_to_1
================== 3 failed, 379 passed, 18 skipped in 41.60s ==================
```

**Comment by mathematicalmichael** [comment]
hold the phone. https://github.com/mathematicalmichael/BET/runs/861417896?check_suite_focus=true 
I'm testing using the BET I built yesterday. probably should be more careful and re-build, despite the only thing changing being the test folder (which is mounted into the runtime env)

**Comment by mathematicalmichael** [comment]
okay, freshly compiled on latest master and it looks like n=2 passes, so I'm re-running the action linked above (which errored in a way I hadn't seen before).

I just ran `n=2,3,4,8` fresh and can confirm same results as above. 8 still fails, the rest are fine.

**Comment by smattis** [comment]
#398 should make these tests pass with any number of cores

**Comment by mathematicalmichael** [comment]
all good!
