### ISSUE TITLE
Tests_and_parallel

### ISSUE THREAD

**Issue by lcgraham** [UT-CHG/BET#90]
@smattis is the tests_and_parallel branch ready for merging? If so want me to go ahead and merge it to master?

**Comment by smattis** [comment]
No. It is not ready yet.

On Tue, Jun 9, 2015 at 11:16 AM, Lindley Graham <notifications@github.com>
wrote:

> @smattis <https://github.com/smattis> is the tests_and_parallel branch
> ready for merging? If so want me to go ahead and merge it to master?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/UT-CHG/BET/issues/90>.
>



-- 
Postdoctoral Research Fellow
Institute for Computational Engineering and Sciences
The University of Texas at Austin
